### ISSUE TITLE
Project 6 : Carbon emissions by country and by year

### ISSUE THREAD

**Issue by GBilocq** [ptds2021/project--G6#1]
- [x] **Step 1** : An Awesome project ! 

- [x] **Step 2** : A super R-package that can be directly installed from your GitHub repository. More specifically you should make sure:

- [x]  you have a DESCRIPTION file with all necessary information including, but not limited to, Package title, general description, dependencies, license, and imports.

- [x] R/Rcpp functions with documentation including title, description, parameters, authors, exports, and at least one example.
- [x] Function 1 : A world map for a year with countries colored by carbon footprint
- [x] Function 2 : A function with the time series of carbon footprint for one or more countries ( in addition possibility to forecast )
- [x] Function 3 : a summary statistic and graphs for a country 

- [x] A well formatted package skeleton (man, inst, docs, R, etc.)

- [x] A shiny app to allow someone having absolutely no R knowledge to “use” what you have done in your project. This shiny app should be within your package.

- [x] The package can seamlessly be installed from your GitHub repository (for example using remotes::install_github("ptds2021/projectGX") where X is your group number.

- [x] A vignette that illustrates your package/shiny app with nice examples

- [x]  **Step 3** : The GitHub repository is well-documented with nice commit messages and clear issues (close them once done!) Up-to-date GitHub projects that demonstrate your current organization for the project : 

- [x] ToDOs

- [x] Tasks in progress of resolution

- [x] Tasks that have been completed

- [x] **Step 4** : A website built using blogdown showcasing your work and your package.

- [x] Motivate the package

- [x] Explain how to use it 

- [x] Video showing the use of the package

**Comment by start97** [comment]
Close issue
